### ISSUE TITLE
Installed but not working

### ISSUE THREAD

**Issue by armintabari** [hepcat72/CFF#3]
**After installing muscle and usearch and perl with no error, I installed the package with no apparent erorr:**

ArminMac:CFF-master armin$ perl Makefile.PL 
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for CFF
Writing MYMETA.yml and MYMETA.json
ArminMac:CFF-master armin$ make
cp src/cff2qiime.pl blib/script/cff2qiime.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/cff2qiime.pl
cp src/getCandidates.pl blib/script/getCandidates.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/getCandidates.pl
cp src/run_CFF_on_FastA.tcsh blib/script/run_CFF_on_FastA.tcsh
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/run_CFF_on_FastA.tcsh
cp src/nZeros.pl blib/script/nZeros.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/nZeros.pl
cp src/run_CFF_on_FastQ.tcsh blib/script/run_CFF_on_FastQ.tcsh
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/run_CFF_on_FastQ.tcsh
cp src/errorRates.pl blib/script/errorRates.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/errorRates.pl
cp src/mergeSeqs.pl blib/script/mergeSeqs.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/mergeSeqs.pl
cp src/interestingPairs.pl blib/script/interestingPairs.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/interestingPairs.pl
cp src/filterIndels.pl blib/script/filterIndels.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/filterIndels.pl
cp src/neighbors.pl blib/script/neighbors.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/neighbors.pl
cp src/getReals.pl blib/script/getReals.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/getReals.pl
ArminMac:CFF-master armin$ sudo make install
Password:
Appending installation info to /Users/armin/perl5/lib/perl5/darwin-2level/perllocal.pod
ArminMac:CFF-master armin$

**Then I tried the test run:**

ArminMac:test armin$ tcsh run_test.tcsh 
Running samples/run_example1.tcsh. Please wait.
cut: ../samples/Caporaso_FASTA_out/4_reals_table/global_library.fna.smry: No such file or directory
Test 1 failed. Your installation does not appear to be working as expected. Please contact rleach@princeton.edu for help.
ArminMac:test armin$

**Then, I tried running one of the samples:**

ArminMac:samples armin$ tcsh run_example3.tcsh 
## RUNNING run_CFF_on_FastQ.tcsh

Start time:                  Fri Apr 17 18:23:01 EDT 2015
Trim length:                 130
Z-score threshold:           2
Magnitude over N0 Threshold: 10
Nominations threshold:       2
Fastq ASCII:                 64
Trunc. Quality:              2
OUTPUT DIRECTORY:            Caporaso_GutSamples_out

usearch -fastq_filter     Caporaso_GutSamples/1_335.fastq -fastq_trunclen 130 -fastq_maxee 1 -fastaout Caporaso_GutSamples_out/0_1_qc/1_335.fastq.qc.fna -relabel 1_335.fastq_ -eeout -fastq_ascii 64 -fastq_truncqual 2 -quiet -- 3 seconds
usearch -derep_fulllength Caporaso_GutSamples_out/0_1_qc/1_335.fastq.qc.fna -output Caporaso_GutSamples_out/0_2_drp/1_335.fastq.drp.fna -sizeout -quiet -- 0 seconds
usearch -fastq_filter     Caporaso_GutSamples/F4_Apr09.fastq -fastq_trunclen 130 -fastq_maxee 1 -fastaout Caporaso_GutSamples_out/0_1_qc/F4_Apr09.fastq.qc.fna -relabel F4_Apr09.fastq_ -eeout -fastq_ascii 64 -fastq_truncqual 2 -quiet -- 2 seconds
usearch -derep_fulllength Caporaso_GutSamples_out/0_1_qc/F4_Apr09.fastq.qc.fna -output Caporaso_GutSamples_out/0_2_drp/F4_Apr09.fastq.drp.fna -sizeout -quiet -- 0 seconds
usearch -fastq_filter     Caporaso_GutSamples/F4_Jan09.fastq -fastq_trunclen 130 -fastq_maxee 1 -fastaout Caporaso_GutSamples_out/0_1_qc/F4_Jan09.fastq.qc.fna -relabel F4_Jan09.fastq_ -eeout -fastq_ascii 64 -fastq_truncqual 2 -quiet -- 2 seconds
usearch -derep_fulllength Caporaso_GutSamples_out/0_1_qc/F4_Jan09.fastq.qc.fna -output Caporaso_GutSamples_out/0_2_drp/F4_Jan09.fastq.drp.fna -sizeout -quiet -- 1 seconds
usearch -fastq_filter     Caporaso_GutSamples/F4_Oct08.fastq -fastq_trunclen 130 -fastq_maxee 1 -fastaout Caporaso_GutSamples_out/0_1_qc/F4_Oct08.fastq.qc.fna -relabel F4_Oct08.fastq_ -eeout -fastq_ascii 64 -fastq_truncqual 2 -quiet -- 1 seconds
usearch -derep_fulllength Caporaso_GutSamples_out/0_1_qc/F4_Oct08.fastq.qc.fna -output Caporaso_GutSamples_out/0_2_drp/F4_Oct08.fastq.drp.fna -sizeout -quiet -- 1 seconds
usearch -fastq_filter     Caporaso_GutSamples/M3_Apr09.fastq -fastq_trunclen 130 -fastq_maxee 1 -fastaout Caporaso_GutSamples_out/0_1_qc/M3_Apr09.fastq.qc.fna -relabel M3_Apr09.fastq_ -eeout -fastq_ascii 64 -fastq_truncqual 2 -quiet -- 2 seconds
usearch -derep_fulllength Caporaso_GutSamples_out/0_1_qc/M3_Apr09.fastq.qc.fna -output Caporaso_GutSamples_out/0_2_drp/M3_Apr09.fastq.drp.fna -sizeout -quiet -- 1 seconds
usearch -fastq_filter     Caporaso_GutSamples/M3_Jan09.fastq -fastq_trunclen 130 -fastq_maxee 1 -fastaout Caporaso_GutSamples_out/0_1_qc/M3_Jan09.fastq.qc.fna -relabel M3_Jan09.fastq_ -eeout -fastq_ascii 64 -fastq_truncqual 2 -quiet -- 3 seconds
usearch -derep_fulllength Caporaso_GutSamples_out/0_1_qc/M3_Jan09.fastq.qc.fna -output Caporaso_GutSamples_out/0_2_drp/M3_Jan09.fastq.drp.fna -sizeout -quiet -- 0 seconds
usearch -fastq_filter     Caporaso_GutSamples/M3_Oct08.fastq -fastq_trunclen 130 -fastq_maxee 1 -fastaout Caporaso_GutSamples_out/0_1_qc/M3_Oct08.fastq.qc.fna -relabel M3_Oct08.fastq_ -eeout -fastq_ascii 64 -fastq_truncqual 2 -quiet -- 2 seconds
usearch -derep_fulllength Caporaso_GutSamples_out/0_1_qc/M3_Oct08.fastq.qc.fna -output Caporaso_GutSamples_out/0_2_drp/M3_Oct08.fastq.drp.fna -sizeout -quiet -- 0 seconds

mergeSeqs.pl        'Caporaso_GutSamples_out/0_2_drp/{*.fastq}.drp.fna' -f 'global_library.fna' --outdir 'Caporaso_GutSamples_out/1_lib' -o .lib -t fastamergeSeqs.pl: Command not found.

ERROR: Command mergeSeqs.pl failed
Stop time: Fri Apr 17 18:23:19 EDT 2015
RUN TIME:  18 seconds

ArminMac:samples armin$ 

**I did everything over and over. On Mac OS X 10.10**

**Comment by hepcat72** [comment]
Hi Armin,

It appears that the shell script does not know where the perl scripts are.  Note, at the end of the mergeSeqs.pl command, there is an error (it's at the end of that line):

"mergeSeqs.pl: Command not found."

I colored that in bold red in your quoted email below.  Tell me, what do you get when you run these two commands in the terminal where you ran the test and the example:

which mergeSeqs.pl
echo $PATH

Your default perl installation appears to be /usr/local/bin/perl, and it must be in your path since the `perl MakeFile.PL` command worked - are you using multiple terminal windows?

If you do not get the path of the mergeSeqs.pl script from the `which` command, you might just need to open a new terminal window to get a fresh environment.  If you do get the path, what path did it give you?

Rob

Robert William Leach
133A Carl C. Icahn Lab
Lewis-Sigler Institute for Integrative Genomics
Princeton University
Princeton, NJ 08544

**Comment by hepcat72** [comment]
Rob,

Here is the output you asked for:

ArminMac:src armin$ which perl
/usr/local/bin/perl
ArminMac:src armin$ which mergeSeqs.pl
ArminMac:src armin$ echo $PATH
/Users/armin/Uni/FodorLab:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/armin/Uni/FodorLab:/opt/X11/bin

I am using the same terminal window for all. The which command does not return anything for mergeSeqs.pl but it is there at the .../CFF-master/blib/script address.

On Apr 17, 2015, at 7:33 PM, Robert William Leach <rleach@genomics.princeton.edu<mailto:rleach@genomics.princeton.edu>> wrote:

Hi Armin,

It appears that the shell script does not know where the perl scripts are.  Note, at the end of the mergeSeqs.pl command, there is an error (it's at the end of that line):

"mergeSeqs.pl: Command not found."

I colored that in bold red in your quoted email below.  Tell me, what do you get when you run these two commands in the terminal where you ran the test and the example:

which mergeSeqs.pl
echo $PATH

Your default perl installation appears to be /usr/local/bin/perl, and it must be in your path since the `perl MakeFile.PL` command worked - are you using multiple terminal windows?

If you do not get the path of the mergeSeqs.pl script from the `which` command, you might just need to open a new terminal window to get a fresh environment.  If you do get the path, what path did it give you?

Rob

Robert William Leach
133A Carl C. Icahn Lab
Lewis-Sigler Institute for Integrative Genomics
Princeton University
Princeton, NJ 08544

On Apr 17, 2015, at 7:12 PM, Armin Tabari <notifications@github.com<mailto:notifications@github.com>> wrote:

After installing muscle and usearch and perl with no error, I installed the package with no apparent erorr:

ArminMac:CFF-master armin$ perl Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for CFF
Writing MYMETA.yml and MYMETA.json
ArminMac:CFF-master armin$ make
cp src/cff2qiime.pl blib/script/cff2qiime.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/cff2qiime.pl
cp src/getCandidates.pl blib/script/getCandidates.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/getCandidates.pl
cp src/run_CFF_on_FastA.tcsh blib/script/run_CFF_on_FastA.tcsh
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/run_CFF_on_FastA.tcsh
cp src/nZeros.pl blib/script/nZeros.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/nZeros.pl
cp src/run_CFF_on_FastQ.tcsh blib/script/run_CFF_on_FastQ.tcsh
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/run_CFF_on_FastQ.tcsh
cp src/errorRates.pl blib/script/errorRates.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/errorRates.pl
cp src/mergeSeqs.pl blib/script/mergeSeqs.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/mergeSeqs.pl
cp src/interestingPairs.pl blib/script/interestingPairs.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/interestingPairs.pl
cp src/filterIndels.pl blib/script/filterIndels.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/filterIndels.pl
cp src/neighbors.pl blib/script/neighbors.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/neighbors.pl
cp src/getReals.pl blib/script/getReals.pl
/usr/local/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/getReals.pl
ArminMac:CFF-master armin$ sudo make install
Password:
Appending installation info to /Users/armin/perl5/lib/perl5/darwin-2level/perllocal.pod
ArminMac:CFF-master armin$

Then I tried the test run:

ArminMac:test armin$ tcsh run_test.tcsh
Running samples/run_example1.tcsh. Please wait.
cut: ../samples/Caporaso_FASTA_out/4_reals_table/global_library.fna.smry: No such file or directory
Test 1 failed. Your installation does not appear to be working as expected. Please contact rleach@princeton.edumailto:rleach@princeton.edu for help.
ArminMac:test armin$

Then, I tried running one of the samples:

ArminMac:samples armin$ tcsh run_example3.tcsh

RUNNING run_CFF_on_FastQ.tcsh

Start time: Fri Apr 17 18:23:01 EDT 2015
Trim length: 130
Z-score threshold: 2
Magnitude over N0 Threshold: 10
Nominations threshold: 2
Fastq ASCII: 64
Trunc. Quality: 2
OUTPUT DIRECTORY: Caporaso_GutSamples_out

usearch -fastq_filter Caporaso_GutSamples/1_335.fastq -fastq_trunclen 130 -fastq_maxee 1 -fastaout Caporaso_GutSamples_out/0_1_qc/1_335.fastq.qc.fna -relabel 1_335.fastq_ -eeout -fastq_ascii 64 -fastq_truncqual 2 -quiet -- 3 seconds
usearch -derep_fulllength Caporaso_GutSamples_out/0_1_qc/1_335.fastq.qc.fna -output Caporaso_GutSamples_out/0_2_drp/1_335.fastq.drp.fna -sizeout -quiet -- 0 seconds
usearch -fastq_filter Caporaso_GutSamples/F4_Apr09.fastq -fastq_trunclen 130 -fastq_maxee 1 -fastaout Caporaso_GutSamples_out/0_1_qc/F4_Apr09.fastq.qc.fna -relabel F4_Apr09.fastq_ -eeout -fastq_ascii 64 -fastq_truncqual 2 -quiet -- 2 seconds
usearch -derep_fulllength Caporaso_GutSamples_out/0_1_qc/F4_Apr09.fastq.qc.fna -output Caporaso_GutSamples_out/0_2_drp/F4_Apr09.fastq.drp.fna -sizeout -quiet -- 0 seconds
usearch -fastq_filter Caporaso_GutSamples/F4_Jan09.fastq -fastq_trunclen 130 -fastq_maxee 1 -fastaout Caporaso_GutSamples_out/0_1_qc/F4_Jan09.fastq.qc.fna -relabel F4_Jan09.fastq_ -eeout -fastq_ascii 64 -fastq_truncqual 2 -quiet -- 2 seconds
usearch -derep_fulllength Caporaso_GutSamples_out/0_1_qc/F4_Jan09.fastq.qc.fna -output Caporaso_GutSamples_out/0_2_drp/F4_Jan09.fastq.drp.fna -sizeout -quiet -- 1 seconds
usearch -fastq_filter Caporaso_GutSamples/F4_Oct08.fastq -fastq_trunclen 130 -fastq_maxee 1 -fastaout Caporaso_GutSamples_out/0_1_qc/F4_Oct08.fastq.qc.fna -relabel F4_Oct08.fastq_ -eeout -fastq_ascii 64 -fastq_truncqual 2 -quiet -- 1 seconds
usearch -derep_fulllength Caporaso_GutSamples_out/0_1_qc/F4_Oct08.fastq.qc.fna -output Caporaso_GutSamples_out/0_2_drp/F4_Oct08.fastq.drp.fna -sizeout -quiet -- 1 seconds
usearch -fastq_filter Caporaso_GutSamples/M3_Apr09.fastq -fastq_trunclen 130 -fastq_maxee 1 -fastaout Caporaso_GutSamples_out/0_1_qc/M3_Apr09.fastq.qc.fna -relabel M3_Apr09.fastq_ -eeout -fastq_ascii 64 -fastq_truncqual 2 -quiet -- 2 seconds
usearch -derep_fulllength Caporaso_GutSamples_out/0_1_qc/M3_Apr09.fastq.qc.fna -output Caporaso_GutSamples_out/0_2_drp/M3_Apr09.fastq.drp.fna -sizeout -quiet -- 1 seconds
usearch -fastq_filter Caporaso_GutSamples/M3_Jan09.fastq -fastq_trunclen 130 -fastq_maxee 1 -fastaout Caporaso_GutSamples_out/0_1_qc/M3_Jan09.fastq.qc.fna -relabel M3_Jan09.fastq_ -eeout -fastq_ascii 64 -fastq_truncqual 2 -quiet -- 3 seconds
usearch -derep_fulllength Caporaso_GutSamples_out/0_1_qc/M3_Jan09.fastq.qc.fna -output Caporaso_GutSamples_out/0_2_drp/M3_Jan09.fastq.drp.fna -sizeout -quiet -- 0 seconds
usearch -fastq_filter Caporaso_GutSamples/M3_Oct08.fastq -fastq_trunclen 130 -fastq_maxee 1 -fastaout Caporaso_GutSamples_out/0_1_qc/M3_Oct08.fastq.qc.fna -relabel M3_Oct08.fastq_ -eeout -fastq_ascii 64 -fastq_truncqual 2 -quiet -- 2 seconds
usearch -derep_fulllength Caporaso_GutSamples_out/0_1_qc/M3_Oct08.fastq.qc.fna -output Caporaso_GutSamples_out/0_2_drp/M3_Oct08.fastq.drp.fna -sizeout -quiet -- 0 seconds

mergeSeqs.pl 'Caporaso_GutSamples_out/0_2_drp/{*.fastq}.drp.fna' -f 'global_library.fna' --outdir 'Caporaso_GutSamples_out/1_lib' -o .lib -t fastamergeSeqs.pl: Command not found.

ERROR: Command mergeSeqs.pl failed
Stop time: Fri Apr 17 18:23:19 EDT 2015
RUN TIME: 18 seconds

ArminMac:samples armin$

I did everything over and over. On Mac OS X 10.10

**Comment by hepcat72** [comment]
Hi Armin,

All of the scripts assume that the elements if CFF are in your path. They don't use the versions inside ".../CFF-master/blib/script". 'sudo make install' copies the necessary CFF scripts to your default location, which appears to be /usr/local/bin. However, for some reason, that step did not appear to work or else copied them to a location not in your path.

I suggest you either try to run the make install command again, put the path to the scripts in your PATH variable, or copy the contents of .../CFF-master/blib/script to /usr/local/bin.

Best,
Rob
